# version:   "0000--12-Sep-2022"
copyright:   "2022"
author:      "matthewrizkyhartadi"
name:        "Matthew Rizky Hartadi"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/Matthew-Rizky-Hartadi/os222/"
myloglink:   "/TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
